server:
  servlet:
    context-path: /oficina-da-informatica/api

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/oficina-da-informatica
    username: postgres
    password: 852456
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true
        format_sql: true

springdoc:
  swagger-ui:
    path: /public/swagger